version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    #volumes:
    # - .:/home/oorgien/code/Project2
    environment:
      FLASK_ENV: debug
  redis:
    image: "redis:alpine"
